### PR TITLE
redirect site to devops brisbane 2014

### PR DESCRIPTION
**Pull request by gergnz**

### CODE REVIEW

**Comment by mattcallanan** [comment]
@auxesis can you please perform this pull request? devopsdownunder.org still points to http://www.devopsdays.org/events/2013-downunder/

**Comment by auxesis** [comment]
@mattcallanan done, apologies for taking so long.

**Comment by mattcallanan** [comment]
Thanks @auxesis - it's still going to 2013-downunder... do we need to restart the server to apply the change to the website? @gergnz ?  Thanks.

**Comment by auxesis** [comment]
The site isn't hosted on gh-pages, it's still pointing to an old VPS of mine. 

Have done a force push, am investigating pointing it over to gh-pages. 

```
$ curl -v devopsdownunder.org
* About to connect() to devopsdownunder.org port 80 (#0)
*   Trying 202.177.222.214...
* connected
* Connected to devopsdownunder.org (202.177.222.214) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.24.0 (x86_64-apple-darwin12.0) libcurl/7.24.0 OpenSSL/0.9.8y zlib/1.2.5
> Host: devopsdownunder.org
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Mon, 19 May 2014 05:37:06 GMT
< Server: Apache/2.2.8 (Ubuntu) Phusion_Passenger/2.0.3 mod_ssl/2.2.8 OpenSSL/0.9.8g
< Last-Modified: Mon, 19 May 2014 05:35:33 GMT
< ETag: "7d6b1-f0-4f9ba21ca9340"
< Accept-Ranges: bytes
< Content-Length: 240
< Content-Type: text/html
<
<html>
  <head>
    <meta http-equiv="refresh" content="0; url=http://www.devopsdays.org/events/2014-brisbane/" />
  </head>
 <body>
   <a href="http://www.devopsdays.org/events/2014-brisbane/">DevOpsDays Brisbane 2014</a>
 </body>
</html>
* Connection #0 to host devopsdownunder.org left intact
* Closing connection #0
```

**Comment by mattcallanan** [comment]
Thanks Lindsay

**Pull request merged**
